#!/bin/zsh -e

docker compose up -d mysql mariadb postgres

export SHIORI_TEST_PG_URL="postgres://shiori:shiori@localhost:5432/shiori?sslmode=disable"
export SHIORI_TEST_MYSQL_URL="shiori:shiori@(localhost:3306)/shiori"
export SHIORI_TEST_MARIADB_URL="shiori:shiori@(localhost:3307)/shiori"

make lint

make unittest GOTESTFMT_FLAGS="-hide all"
