# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: -1
# Issues with these labels will never be considered stale
exemptLabels:
- tag:no-stale
- type:bug
- type:enhancement
- type:documentation
# Label to use when marking an issue as stale
staleLabel: tag:stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had any
  activity for quite some time.

  It will be closed if no further activity occurs.

  Thank you for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

pulls:
  daysUntilStale: 10
  daysUntilClose: -1
  onlyLabels:
    - tag:stalebot
