/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1BookmarkDataResponse
 */
export interface ApiV1BookmarkDataResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiV1BookmarkDataResponse
     */
    archiveURL?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BookmarkDataResponse
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BookmarkDataResponse
     */
    ebookURL?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1BookmarkDataResponse
     */
    hasArchive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1BookmarkDataResponse
     */
    hasContent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1BookmarkDataResponse
     */
    hasEbook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1BookmarkDataResponse
     */
    hasThumbnail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BookmarkDataResponse
     */
    html?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1BookmarkDataResponse
     */
    imageURL?: string;
}

/**
 * Check if a given object implements the ApiV1BookmarkDataResponse interface.
 */
export function instanceOfApiV1BookmarkDataResponse(value: object): value is ApiV1BookmarkDataResponse {
    return true;
}

export function ApiV1BookmarkDataResponseFromJSON(json: any): ApiV1BookmarkDataResponse {
    return ApiV1BookmarkDataResponseFromJSONTyped(json, false);
}

export function ApiV1BookmarkDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1BookmarkDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveURL': json['archiveURL'] == null ? undefined : json['archiveURL'],
        'content': json['content'] == null ? undefined : json['content'],
        'ebookURL': json['ebookURL'] == null ? undefined : json['ebookURL'],
        'hasArchive': json['hasArchive'] == null ? undefined : json['hasArchive'],
        'hasContent': json['hasContent'] == null ? undefined : json['hasContent'],
        'hasEbook': json['hasEbook'] == null ? undefined : json['hasEbook'],
        'hasThumbnail': json['hasThumbnail'] == null ? undefined : json['hasThumbnail'],
        'html': json['html'] == null ? undefined : json['html'],
        'imageURL': json['imageURL'] == null ? undefined : json['imageURL'],
    };
}

export function ApiV1BookmarkDataResponseToJSON(json: any): ApiV1BookmarkDataResponse {
    return ApiV1BookmarkDataResponseToJSONTyped(json, false);
}

export function ApiV1BookmarkDataResponseToJSONTyped(value?: ApiV1BookmarkDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archiveURL': value['archiveURL'],
        'content': value['content'],
        'ebookURL': value['ebookURL'],
        'hasArchive': value['hasArchive'],
        'hasContent': value['hasContent'],
        'hasEbook': value['hasEbook'],
        'hasThumbnail': value['hasThumbnail'],
        'html': value['html'],
        'imageURL': value['imageURL'],
    };
}

