/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UpdateBookmarkDataPayload
 */
export interface ApiV1UpdateBookmarkDataPayload {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    create_archive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    create_ebook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    keep_metadata?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    skip_existing?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    update_readable?: boolean;
}

/**
 * Check if a given object implements the ApiV1UpdateBookmarkDataPayload interface.
 */
export function instanceOfApiV1UpdateBookmarkDataPayload(value: object): value is ApiV1UpdateBookmarkDataPayload {
    return true;
}

export function ApiV1UpdateBookmarkDataPayloadFromJSON(json: any): ApiV1UpdateBookmarkDataPayload {
    return ApiV1UpdateBookmarkDataPayloadFromJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkDataPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UpdateBookmarkDataPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'create_archive': json['create_archive'] == null ? undefined : json['create_archive'],
        'create_ebook': json['create_ebook'] == null ? undefined : json['create_ebook'],
        'keep_metadata': json['keep_metadata'] == null ? undefined : json['keep_metadata'],
        'skip_existing': json['skip_existing'] == null ? undefined : json['skip_existing'],
        'update_readable': json['update_readable'] == null ? undefined : json['update_readable'],
    };
}

export function ApiV1UpdateBookmarkDataPayloadToJSON(json: any): ApiV1UpdateBookmarkDataPayload {
    return ApiV1UpdateBookmarkDataPayloadToJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkDataPayloadToJSONTyped(value?: ApiV1UpdateBookmarkDataPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_archive': value['create_archive'],
        'create_ebook': value['create_ebook'],
        'keep_metadata': value['keep_metadata'],
        'skip_existing': value['skip_existing'],
        'update_readable': value['update_readable'],
    };
}

