/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UpdateBookmarkDataPayload
 */
export interface ApiV1UpdateBookmarkDataPayload {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    createArchive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    createEbook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    keepMetadata?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    skipExisting?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateBookmarkDataPayload
     */
    updateReadable?: boolean;
}

/**
 * Check if a given object implements the ApiV1UpdateBookmarkDataPayload interface.
 */
export function instanceOfApiV1UpdateBookmarkDataPayload(value: object): value is ApiV1UpdateBookmarkDataPayload {
    return true;
}

export function ApiV1UpdateBookmarkDataPayloadFromJSON(json: any): ApiV1UpdateBookmarkDataPayload {
    return ApiV1UpdateBookmarkDataPayloadFromJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkDataPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UpdateBookmarkDataPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'createArchive': json['create_archive'] == null ? undefined : json['create_archive'],
        'createEbook': json['create_ebook'] == null ? undefined : json['create_ebook'],
        'keepMetadata': json['keep_metadata'] == null ? undefined : json['keep_metadata'],
        'skipExisting': json['skip_existing'] == null ? undefined : json['skip_existing'],
        'updateReadable': json['update_readable'] == null ? undefined : json['update_readable'],
    };
}

export function ApiV1UpdateBookmarkDataPayloadToJSON(json: any): ApiV1UpdateBookmarkDataPayload {
    return ApiV1UpdateBookmarkDataPayloadToJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkDataPayloadToJSONTyped(value?: ApiV1UpdateBookmarkDataPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_archive': value['createArchive'],
        'create_ebook': value['createEbook'],
        'keep_metadata': value['keepMetadata'],
        'skip_existing': value['skipExisting'],
        'update_readable': value['updateReadable'],
    };
}

