/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1DeleteBookmarksPayload
 */
export interface ApiV1DeleteBookmarksPayload {
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiV1DeleteBookmarksPayload
     */
    ids: Array<number>;
}

/**
 * Check if a given object implements the ApiV1DeleteBookmarksPayload interface.
 */
export function instanceOfApiV1DeleteBookmarksPayload(value: object): value is ApiV1DeleteBookmarksPayload {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function ApiV1DeleteBookmarksPayloadFromJSON(json: any): ApiV1DeleteBookmarksPayload {
    return ApiV1DeleteBookmarksPayloadFromJSONTyped(json, false);
}

export function ApiV1DeleteBookmarksPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1DeleteBookmarksPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function ApiV1DeleteBookmarksPayloadToJSON(json: any): ApiV1DeleteBookmarksPayload {
    return ApiV1DeleteBookmarksPayloadToJSONTyped(json, false);
}

export function ApiV1DeleteBookmarksPayloadToJSONTyped(value?: ApiV1DeleteBookmarksPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

