/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1CreateBookmarkPayload
 */
export interface ApiV1CreateBookmarkPayload {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1CreateBookmarkPayload
     */
    createEbook?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CreateBookmarkPayload
     */
    excerpt?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1CreateBookmarkPayload
     */
    _public?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiV1CreateBookmarkPayload
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CreateBookmarkPayload
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1CreateBookmarkPayload
     */
    url: string;
}

/**
 * Check if a given object implements the ApiV1CreateBookmarkPayload interface.
 */
export function instanceOfApiV1CreateBookmarkPayload(value: object): value is ApiV1CreateBookmarkPayload {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function ApiV1CreateBookmarkPayloadFromJSON(json: any): ApiV1CreateBookmarkPayload {
    return ApiV1CreateBookmarkPayloadFromJSONTyped(json, false);
}

export function ApiV1CreateBookmarkPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1CreateBookmarkPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'createEbook': json['create_ebook'] == null ? undefined : json['create_ebook'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        '_public': json['public'] == null ? undefined : json['public'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'],
    };
}

export function ApiV1CreateBookmarkPayloadToJSON(json: any): ApiV1CreateBookmarkPayload {
    return ApiV1CreateBookmarkPayloadToJSONTyped(json, false);
}

export function ApiV1CreateBookmarkPayloadToJSONTyped(value?: ApiV1CreateBookmarkPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_ebook': value['createEbook'],
        'excerpt': value['excerpt'],
        'public': value['_public'],
        'tags': value['tags'],
        'title': value['title'],
        'url': value['url'],
    };
}

