/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UpdateBookmarkPayload
 */
export interface ApiV1UpdateBookmarkPayload {
    /**
     * 
     * @type {string}
     * @memberof ApiV1UpdateBookmarkPayload
     */
    excerpt?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiV1UpdateBookmarkPayload
     */
    _public?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UpdateBookmarkPayload
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1UpdateBookmarkPayload
     */
    url?: string;
}

/**
 * Check if a given object implements the ApiV1UpdateBookmarkPayload interface.
 */
export function instanceOfApiV1UpdateBookmarkPayload(value: object): value is ApiV1UpdateBookmarkPayload {
    return true;
}

export function ApiV1UpdateBookmarkPayloadFromJSON(json: any): ApiV1UpdateBookmarkPayload {
    return ApiV1UpdateBookmarkPayloadFromJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UpdateBookmarkPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        '_public': json['public'] == null ? undefined : json['public'],
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ApiV1UpdateBookmarkPayloadToJSON(json: any): ApiV1UpdateBookmarkPayload {
    return ApiV1UpdateBookmarkPayloadToJSONTyped(json, false);
}

export function ApiV1UpdateBookmarkPayloadToJSONTyped(value?: ApiV1UpdateBookmarkPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'excerpt': value['excerpt'],
        'public': value['_public'],
        'title': value['title'],
        'url': value['url'],
    };
}

