/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1UpdateCachePayload
 */
export interface ApiV1UpdateCachePayload {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateCachePayload
     */
    create_archive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateCachePayload
     */
    create_ebook?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiV1UpdateCachePayload
     */
    ids: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateCachePayload
     */
    keep_metadata?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1UpdateCachePayload
     */
    skip_exist?: boolean;
}

/**
 * Check if a given object implements the ApiV1UpdateCachePayload interface.
 */
export function instanceOfApiV1UpdateCachePayload(value: object): value is ApiV1UpdateCachePayload {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function ApiV1UpdateCachePayloadFromJSON(json: any): ApiV1UpdateCachePayload {
    return ApiV1UpdateCachePayloadFromJSONTyped(json, false);
}

export function ApiV1UpdateCachePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1UpdateCachePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'create_archive': json['create_archive'] == null ? undefined : json['create_archive'],
        'create_ebook': json['create_ebook'] == null ? undefined : json['create_ebook'],
        'ids': json['ids'],
        'keep_metadata': json['keep_metadata'] == null ? undefined : json['keep_metadata'],
        'skip_exist': json['skip_exist'] == null ? undefined : json['skip_exist'],
    };
}

export function ApiV1UpdateCachePayloadToJSON(json: any): ApiV1UpdateCachePayload {
    return ApiV1UpdateCachePayloadToJSONTyped(json, false);
}

export function ApiV1UpdateCachePayloadToJSONTyped(value?: ApiV1UpdateCachePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_archive': value['create_archive'],
        'create_ebook': value['create_ebook'],
        'ids': value['ids'],
        'keep_metadata': value['keep_metadata'],
        'skip_exist': value['skip_exist'],
    };
}

