/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1CreateBookmarkOptions
 */
export interface ApiV1CreateBookmarkOptions {
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1CreateBookmarkOptions
     */
    create_archive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApiV1CreateBookmarkOptions
     */
    create_ebook?: boolean;
}

/**
 * Check if a given object implements the ApiV1CreateBookmarkOptions interface.
 */
export function instanceOfApiV1CreateBookmarkOptions(value: object): value is ApiV1CreateBookmarkOptions {
    return true;
}

export function ApiV1CreateBookmarkOptionsFromJSON(json: any): ApiV1CreateBookmarkOptions {
    return ApiV1CreateBookmarkOptionsFromJSONTyped(json, false);
}

export function ApiV1CreateBookmarkOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1CreateBookmarkOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'create_archive': json['create_archive'] == null ? undefined : json['create_archive'],
        'create_ebook': json['create_ebook'] == null ? undefined : json['create_ebook'],
    };
}

export function ApiV1CreateBookmarkOptionsToJSON(json: any): ApiV1CreateBookmarkOptions {
    return ApiV1CreateBookmarkOptionsToJSONTyped(json, false);
}

export function ApiV1CreateBookmarkOptionsToJSONTyped(value?: ApiV1CreateBookmarkOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_archive': value['create_archive'],
        'create_ebook': value['create_ebook'],
    };
}

