/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelBookmarkDTO } from './ModelBookmarkDTO';
import {
    ModelBookmarkDTOFromJSON,
    ModelBookmarkDTOFromJSONTyped,
    ModelBookmarkDTOToJSON,
    ModelBookmarkDTOToJSONTyped,
} from './ModelBookmarkDTO';

/**
 * 
 * @export
 * @interface ModelPaginatedResponseModelBookmarkDTO
 */
export interface ModelPaginatedResponseModelBookmarkDTO {
    /**
     * 
     * @type {Array<ModelBookmarkDTO>}
     * @memberof ModelPaginatedResponseModelBookmarkDTO
     */
    items?: Array<ModelBookmarkDTO>;
    /**
     * 
     * @type {number}
     * @memberof ModelPaginatedResponseModelBookmarkDTO
     */
    total?: number;
}

/**
 * Check if a given object implements the ModelPaginatedResponseModelBookmarkDTO interface.
 */
export function instanceOfModelPaginatedResponseModelBookmarkDTO(value: object): value is ModelPaginatedResponseModelBookmarkDTO {
    return true;
}

export function ModelPaginatedResponseModelBookmarkDTOFromJSON(json: any): ModelPaginatedResponseModelBookmarkDTO {
    return ModelPaginatedResponseModelBookmarkDTOFromJSONTyped(json, false);
}

export function ModelPaginatedResponseModelBookmarkDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPaginatedResponseModelBookmarkDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ModelBookmarkDTOFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ModelPaginatedResponseModelBookmarkDTOToJSON(json: any): ModelPaginatedResponseModelBookmarkDTO {
    return ModelPaginatedResponseModelBookmarkDTOToJSONTyped(json, false);
}

export function ModelPaginatedResponseModelBookmarkDTOToJSONTyped(value?: ModelPaginatedResponseModelBookmarkDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ModelBookmarkDTOToJSON)),
        'total': value['total'],
    };
}

