/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelTagDTO } from './ModelTagDTO';
import {
    ModelTagDTOFromJSON,
    ModelTagDTOFromJSONTyped,
    ModelTagDTOToJSON,
    ModelTagDTOToJSONTyped,
} from './ModelTagDTO';

/**
 * 
 * @export
 * @interface ModelPaginatedResponseModelTagDTO
 */
export interface ModelPaginatedResponseModelTagDTO {
    /**
     * 
     * @type {Array<ModelTagDTO>}
     * @memberof ModelPaginatedResponseModelTagDTO
     */
    items?: Array<ModelTagDTO>;
    /**
     * 
     * @type {number}
     * @memberof ModelPaginatedResponseModelTagDTO
     */
    total?: number;
}

/**
 * Check if a given object implements the ModelPaginatedResponseModelTagDTO interface.
 */
export function instanceOfModelPaginatedResponseModelTagDTO(value: object): value is ModelPaginatedResponseModelTagDTO {
    return true;
}

export function ModelPaginatedResponseModelTagDTOFromJSON(json: any): ModelPaginatedResponseModelTagDTO {
    return ModelPaginatedResponseModelTagDTOFromJSONTyped(json, false);
}

export function ModelPaginatedResponseModelTagDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPaginatedResponseModelTagDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ModelTagDTOFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function ModelPaginatedResponseModelTagDTOToJSON(json: any): ModelPaginatedResponseModelTagDTO {
    return ModelPaginatedResponseModelTagDTOToJSONTyped(json, false);
}

export function ModelPaginatedResponseModelTagDTOToJSONTyped(value?: ModelPaginatedResponseModelTagDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ModelTagDTOToJSON)),
        'total': value['total'],
    };
}

