/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelUserConfig
 */
export interface ModelUserConfig {
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    CreateEbook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    HideExcerpt?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    HideThumbnail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    KeepMetadata?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    ListMode?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    MakePublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    ShowId?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelUserConfig
     */
    Theme?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    UseArchive?: boolean;
}

/**
 * Check if a given object implements the ModelUserConfig interface.
 */
export function instanceOfModelUserConfig(value: object): value is ModelUserConfig {
    return true;
}

export function ModelUserConfigFromJSON(json: any): ModelUserConfig {
    return ModelUserConfigFromJSONTyped(json, false);
}

export function ModelUserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelUserConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'CreateEbook': json['CreateEbook'] == null ? undefined : json['CreateEbook'],
        'HideExcerpt': json['HideExcerpt'] == null ? undefined : json['HideExcerpt'],
        'HideThumbnail': json['HideThumbnail'] == null ? undefined : json['HideThumbnail'],
        'KeepMetadata': json['KeepMetadata'] == null ? undefined : json['KeepMetadata'],
        'ListMode': json['ListMode'] == null ? undefined : json['ListMode'],
        'MakePublic': json['MakePublic'] == null ? undefined : json['MakePublic'],
        'ShowId': json['ShowId'] == null ? undefined : json['ShowId'],
        'Theme': json['Theme'] == null ? undefined : json['Theme'],
        'UseArchive': json['UseArchive'] == null ? undefined : json['UseArchive'],
    };
}

export function ModelUserConfigToJSON(json: any): ModelUserConfig {
    return ModelUserConfigToJSONTyped(json, false);
}

export function ModelUserConfigToJSONTyped(value?: ModelUserConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'CreateEbook': value['CreateEbook'],
        'HideExcerpt': value['HideExcerpt'],
        'HideThumbnail': value['HideThumbnail'],
        'KeepMetadata': value['KeepMetadata'],
        'ListMode': value['ListMode'],
        'MakePublic': value['MakePublic'],
        'ShowId': value['ShowId'],
        'Theme': value['Theme'],
        'UseArchive': value['UseArchive'],
    };
}

