version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - ineffassign
    - predeclared
    - staticcheck
    - unconvert
    - unused
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/mocks
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - internal/mocks
      - third_party$
      - builtin$
      - examples$
