before:
  hooks:
    - go mod tidy
builds:
  - id: linux-amd64
    binary: shiori
    env:
      - CGO_ENABLED=1
    tags:
      - netgo
      - osusergo
      - fts5
    goos:
      - linux
    goarch:
      - amd64
    ignore:
      - goos: darwin
      - goos: windows

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
      arm64: aarch64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  prerelease: auto
