# Docker compose for development purposes only.
# Edit it to fit your current development needs.
services:
  shiori:
    build:
      context: .
      dockerfile: Dockerfile.compose
    container_name: shiori
    command:
      - "server"
      - "--log-level"
      - "debug"
    volumes:
      - "./dev-data:/srv/shiori"
      - ".:/src/shiori"
      - "go-mod-cache:/go/pkg/mod"
    environment:
      SHIORI_DIR: /srv/shiori
      # SHIORI_HTTP_ROOT_PATH: /shiori/
      # SHIORI_DATABASE_URL: mysql://shiori:shiori@(mariadb)/shiori?charset=utf8mb4
      # SHIORI_DATABASE_URL: postgres://shiori:shiori@postgres/shiori?sslmode=disable
    restart: unless-stopped
    links:
      - "postgres"
      - "mariadb"
    expose: # for docker networks
      - "8080"
    networks: [layer-1-network, layer-2-network]
    ports: # for host
      - "8080:8080" # public

  nginx:
    image: nginx:alpine
    volumes:
      - "./testdata/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - shiori
    restart: unless-stopped
    expose: # for docker networks
      - "8081"
    networks: [layer-1-network, layer-2-network]
    ports: # for host
      - "8081:8081" # public

  postgres:
    image: postgres:13.18
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    restart: unless-stopped
    expose: # for docker networks
      - "5432"
    networks: [layer-1-network]
    ports: # for host
      - "127.0.0.1:5432:5432" # local-only

  mariadb:
    image: mariadb:10.5.27
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shiori
      MYSQL_USER: shiori
      MYSQL_PASSWORD: shiori
    restart: unless-stopped
    expose: # for docker networks
      - "3306"
    networks: [layer-1-network]
    ports: # for host
      - "127.0.0.1:3306:3306" # local-only

  mysql:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: shiori
      MYSQL_USER: shiori
      MYSQL_PASSWORD: shiori
    restart: unless-stopped
    expose: # for docker networks
      - "3307"
    networks: [layer-1-network]
    ports: # for host
      - "127.0.0.1:3307:3306" # local-only

volumes:
  go-mod-cache:

networks:
  layer-1-network:
    driver: bridge
  layer-2-network:
    driver: bridge
