package routes

import (
	"github.com/gin-gonic/gin"
	"github.com/go-shiori/shiori/internal/config"
	"github.com/go-shiori/shiori/internal/model"
	"github.com/sirupsen/logrus"
	swaggerfiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/go-shiori/shiori/docs" // docs is generated by Swag CLI, you have to import it.
)

type SwaggerAPIRoutes struct {
	logger *logrus.Logger
	deps   *config.Dependencies
}

func (r *SwaggerAPIRoutes) Setup(g *gin.RouterGroup) model.Routes {
	g.GET("/*any", ginSwagger.WrapHandler(swaggerfiles.Handler))
	return r
}

func NewSwaggerAPIRoutes(logger *logrus.Logger, deps *config.Dependencies) *SwaggerAPIRoutes {
	return &SwaggerAPIRoutes{
		logger: logger,
		deps:   deps,
	}
}
