/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1InfoResponse,
} from '../models/index';
import {
    ApiV1InfoResponseFromJSON,
    ApiV1InfoResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Get general system information like Shiori version, database, and OS
     * Get general system information
     */
    async apiV1SystemInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1InfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/system/info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1InfoResponseFromJSON(jsonValue));
    }

    /**
     * Get general system information like Shiori version, database, and OS
     * Get general system information
     */
    async apiV1SystemInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1InfoResponse> {
        const response = await this.apiV1SystemInfoGetRaw(initOverrides);
        return await response.value();
    }

}
