/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1BookmarkTagPayload
 */
export interface ApiV1BookmarkTagPayload {
    /**
     * 
     * @type {number}
     * @memberof ApiV1BookmarkTagPayload
     */
    tagId: number;
}

/**
 * Check if a given object implements the ApiV1BookmarkTagPayload interface.
 */
export function instanceOfApiV1BookmarkTagPayload(value: object): value is ApiV1BookmarkTagPayload {
    if (!('tagId' in value) || value['tagId'] === undefined) return false;
    return true;
}

export function ApiV1BookmarkTagPayloadFromJSON(json: any): ApiV1BookmarkTagPayload {
    return ApiV1BookmarkTagPayloadFromJSONTyped(json, false);
}

export function ApiV1BookmarkTagPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1BookmarkTagPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'tagId': json['tag_id'],
    };
}

export function ApiV1BookmarkTagPayloadToJSON(json: any): ApiV1BookmarkTagPayload {
    return ApiV1BookmarkTagPayloadToJSONTyped(json, false);
}

export function ApiV1BookmarkTagPayloadToJSONTyped(value?: ApiV1BookmarkTagPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag_id': value['tagId'],
    };
}

