/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1LoginResponseMessage
 */
export interface ApiV1LoginResponseMessage {
    /**
     * 
     * @type {number}
     * @memberof ApiV1LoginResponseMessage
     */
    expires?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiV1LoginResponseMessage
     */
    token?: string;
}

/**
 * Check if a given object implements the ApiV1LoginResponseMessage interface.
 */
export function instanceOfApiV1LoginResponseMessage(value: object): value is ApiV1LoginResponseMessage {
    return true;
}

export function ApiV1LoginResponseMessageFromJSON(json: any): ApiV1LoginResponseMessage {
    return ApiV1LoginResponseMessageFromJSONTyped(json, false);
}

export function ApiV1LoginResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1LoginResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'expires': json['expires'] == null ? undefined : json['expires'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function ApiV1LoginResponseMessageToJSON(json: any): ApiV1LoginResponseMessage {
    return ApiV1LoginResponseMessageToJSONTyped(json, false);
}

export function ApiV1LoginResponseMessageToJSONTyped(value?: ApiV1LoginResponseMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires': value['expires'],
        'token': value['token'],
    };
}

