/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1InfoResponseVersion
 */
export interface ApiV1InfoResponseVersion {
    /**
     * 
     * @type {string}
     * @memberof ApiV1InfoResponseVersion
     */
    commit?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1InfoResponseVersion
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1InfoResponseVersion
     */
    tag?: string;
}

/**
 * Check if a given object implements the ApiV1InfoResponseVersion interface.
 */
export function instanceOfApiV1InfoResponseVersion(value: object): value is ApiV1InfoResponseVersion {
    return true;
}

export function ApiV1InfoResponseVersionFromJSON(json: any): ApiV1InfoResponseVersion {
    return ApiV1InfoResponseVersionFromJSONTyped(json, false);
}

export function ApiV1InfoResponseVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1InfoResponseVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'commit': json['commit'] == null ? undefined : json['commit'],
        'date': json['date'] == null ? undefined : json['date'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function ApiV1InfoResponseVersionToJSON(json: any): ApiV1InfoResponseVersion {
    return ApiV1InfoResponseVersionToJSONTyped(json, false);
}

export function ApiV1InfoResponseVersionToJSONTyped(value?: ApiV1InfoResponseVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commit': value['commit'],
        'date': value['date'],
        'tag': value['tag'],
    };
}

