/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1BulkUpdateBookmarkTagsPayload
 */
export interface ApiV1BulkUpdateBookmarkTagsPayload {
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiV1BulkUpdateBookmarkTagsPayload
     */
    bookmarkIds: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ApiV1BulkUpdateBookmarkTagsPayload
     */
    tagIds: Array<number>;
}

/**
 * Check if a given object implements the ApiV1BulkUpdateBookmarkTagsPayload interface.
 */
export function instanceOfApiV1BulkUpdateBookmarkTagsPayload(value: object): value is ApiV1BulkUpdateBookmarkTagsPayload {
    if (!('bookmarkIds' in value) || value['bookmarkIds'] === undefined) return false;
    if (!('tagIds' in value) || value['tagIds'] === undefined) return false;
    return true;
}

export function ApiV1BulkUpdateBookmarkTagsPayloadFromJSON(json: any): ApiV1BulkUpdateBookmarkTagsPayload {
    return ApiV1BulkUpdateBookmarkTagsPayloadFromJSONTyped(json, false);
}

export function ApiV1BulkUpdateBookmarkTagsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1BulkUpdateBookmarkTagsPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'bookmarkIds': json['bookmark_ids'],
        'tagIds': json['tag_ids'],
    };
}

export function ApiV1BulkUpdateBookmarkTagsPayloadToJSON(json: any): ApiV1BulkUpdateBookmarkTagsPayload {
    return ApiV1BulkUpdateBookmarkTagsPayloadToJSONTyped(json, false);
}

export function ApiV1BulkUpdateBookmarkTagsPayloadToJSONTyped(value?: ApiV1BulkUpdateBookmarkTagsPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bookmark_ids': value['bookmarkIds'],
        'tag_ids': value['tagIds'],
    };
}

