/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV1ReadableResponseMessage
 */
export interface ApiV1ReadableResponseMessage {
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReadableResponseMessage
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1ReadableResponseMessage
     */
    html?: string;
}

/**
 * Check if a given object implements the ApiV1ReadableResponseMessage interface.
 */
export function instanceOfApiV1ReadableResponseMessage(value: object): value is ApiV1ReadableResponseMessage {
    return true;
}

export function ApiV1ReadableResponseMessageFromJSON(json: any): ApiV1ReadableResponseMessage {
    return ApiV1ReadableResponseMessageFromJSONTyped(json, false);
}

export function ApiV1ReadableResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1ReadableResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'html': json['html'] == null ? undefined : json['html'],
    };
}

export function ApiV1ReadableResponseMessageToJSON(json: any): ApiV1ReadableResponseMessage {
    return ApiV1ReadableResponseMessageToJSONTyped(json, false);
}

export function ApiV1ReadableResponseMessageToJSONTyped(value?: ApiV1ReadableResponseMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'html': value['html'],
    };
}

