/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiV1InfoResponseVersion } from './ApiV1InfoResponseVersion';
import {
    ApiV1InfoResponseVersionFromJSON,
    ApiV1InfoResponseVersionFromJSONTyped,
    ApiV1InfoResponseVersionToJSON,
    ApiV1InfoResponseVersionToJSONTyped,
} from './ApiV1InfoResponseVersion';

/**
 * 
 * @export
 * @interface ApiV1InfoResponse
 */
export interface ApiV1InfoResponse {
    /**
     * 
     * @type {string}
     * @memberof ApiV1InfoResponse
     */
    database?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiV1InfoResponse
     */
    os?: string;
    /**
     * 
     * @type {ApiV1InfoResponseVersion}
     * @memberof ApiV1InfoResponse
     */
    version?: ApiV1InfoResponseVersion;
}

/**
 * Check if a given object implements the ApiV1InfoResponse interface.
 */
export function instanceOfApiV1InfoResponse(value: object): value is ApiV1InfoResponse {
    return true;
}

export function ApiV1InfoResponseFromJSON(json: any): ApiV1InfoResponse {
    return ApiV1InfoResponseFromJSONTyped(json, false);
}

export function ApiV1InfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1InfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'database': json['database'] == null ? undefined : json['database'],
        'os': json['os'] == null ? undefined : json['os'],
        'version': json['version'] == null ? undefined : ApiV1InfoResponseVersionFromJSON(json['version']),
    };
}

export function ApiV1InfoResponseToJSON(json: any): ApiV1InfoResponse {
    return ApiV1InfoResponseToJSONTyped(json, false);
}

export function ApiV1InfoResponseToJSONTyped(value?: ApiV1InfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'database': value['database'],
        'os': value['os'],
        'version': ApiV1InfoResponseVersionToJSON(value['version']),
    };
}

