/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelUserConfig } from './ModelUserConfig';
import {
    ModelUserConfigFromJSON,
    ModelUserConfigFromJSONTyped,
    ModelUserConfigToJSON,
    ModelUserConfigToJSONTyped,
} from './ModelUserConfig';

/**
 * 
 * @export
 * @interface ModelAccountDTO
 */
export interface ModelAccountDTO {
    /**
     * 
     * @type {ModelUserConfig}
     * @memberof ModelAccountDTO
     */
    config?: ModelUserConfig;
    /**
     * 
     * @type {number}
     * @memberof ModelAccountDTO
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelAccountDTO
     */
    owner?: boolean;
    /**
     * Used only to store, not to retrieve
     * @type {string}
     * @memberof ModelAccountDTO
     */
    passowrd?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAccountDTO
     */
    username?: string;
}

/**
 * Check if a given object implements the ModelAccountDTO interface.
 */
export function instanceOfModelAccountDTO(value: object): value is ModelAccountDTO {
    return true;
}

export function ModelAccountDTOFromJSON(json: any): ModelAccountDTO {
    return ModelAccountDTOFromJSONTyped(json, false);
}

export function ModelAccountDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccountDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : ModelUserConfigFromJSON(json['config']),
        'id': json['id'] == null ? undefined : json['id'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'passowrd': json['passowrd'] == null ? undefined : json['passowrd'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ModelAccountDTOToJSON(json: any): ModelAccountDTO {
    return ModelAccountDTOToJSONTyped(json, false);
}

export function ModelAccountDTOToJSONTyped(value?: ModelAccountDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': ModelUserConfigToJSON(value['config']),
        'id': value['id'],
        'owner': value['owner'],
        'passowrd': value['passowrd'],
        'username': value['username'],
    };
}

