/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelUserConfig
 */
export interface ModelUserConfig {
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    createEbook?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    hideExcerpt?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    hideThumbnail?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    keepMetadata?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    listMode?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    makePublic?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    showId?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelUserConfig
     */
    theme?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUserConfig
     */
    useArchive?: boolean;
}

/**
 * Check if a given object implements the ModelUserConfig interface.
 */
export function instanceOfModelUserConfig(value: object): value is ModelUserConfig {
    return true;
}

export function ModelUserConfigFromJSON(json: any): ModelUserConfig {
    return ModelUserConfigFromJSONTyped(json, false);
}

export function ModelUserConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelUserConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'createEbook': json['createEbook'] == null ? undefined : json['createEbook'],
        'hideExcerpt': json['hideExcerpt'] == null ? undefined : json['hideExcerpt'],
        'hideThumbnail': json['hideThumbnail'] == null ? undefined : json['hideThumbnail'],
        'keepMetadata': json['keepMetadata'] == null ? undefined : json['keepMetadata'],
        'listMode': json['listMode'] == null ? undefined : json['listMode'],
        'makePublic': json['makePublic'] == null ? undefined : json['makePublic'],
        'showId': json['showId'] == null ? undefined : json['showId'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'useArchive': json['useArchive'] == null ? undefined : json['useArchive'],
    };
}

export function ModelUserConfigToJSON(json: any): ModelUserConfig {
    return ModelUserConfigToJSONTyped(json, false);
}

export function ModelUserConfigToJSONTyped(value?: ModelUserConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createEbook': value['createEbook'],
        'hideExcerpt': value['hideExcerpt'],
        'hideThumbnail': value['hideThumbnail'],
        'keepMetadata': value['keepMetadata'],
        'listMode': value['listMode'],
        'makePublic': value['makePublic'],
        'showId': value['showId'],
        'theme': value['theme'],
        'useArchive': value['useArchive'],
    };
}

