/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelTagDTO } from './ModelTagDTO';
import {
    ModelTagDTOFromJSON,
    ModelTagDTOFromJSONTyped,
    ModelTagDTOToJSON,
    ModelTagDTOToJSONTyped,
} from './ModelTagDTO';

/**
 * 
 * @export
 * @interface ModelBookmarkDTO
 */
export interface ModelBookmarkDTO {
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    author?: string;
    /**
     * TODO: migrate outside the DTO
     * @type {boolean}
     * @memberof ModelBookmarkDTO
     */
    createArchive?: boolean;
    /**
     * TODO: migrate outside the DTO
     * @type {boolean}
     * @memberof ModelBookmarkDTO
     */
    createEbook?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    excerpt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelBookmarkDTO
     */
    hasArchive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelBookmarkDTO
     */
    hasContent?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelBookmarkDTO
     */
    hasEbook?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    html?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelBookmarkDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    imageURL?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    modifiedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelBookmarkDTO
     */
    _public?: number;
    /**
     * 
     * @type {Array<ModelTagDTO>}
     * @memberof ModelBookmarkDTO
     */
    tags?: Array<ModelTagDTO>;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelBookmarkDTO
     */
    url?: string;
}

/**
 * Check if a given object implements the ModelBookmarkDTO interface.
 */
export function instanceOfModelBookmarkDTO(value: object): value is ModelBookmarkDTO {
    return true;
}

export function ModelBookmarkDTOFromJSON(json: any): ModelBookmarkDTO {
    return ModelBookmarkDTOFromJSONTyped(json, false);
}

export function ModelBookmarkDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBookmarkDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'] == null ? undefined : json['author'],
        'createArchive': json['create_archive'] == null ? undefined : json['create_archive'],
        'createEbook': json['create_ebook'] == null ? undefined : json['create_ebook'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'hasArchive': json['hasArchive'] == null ? undefined : json['hasArchive'],
        'hasContent': json['hasContent'] == null ? undefined : json['hasContent'],
        'hasEbook': json['hasEbook'] == null ? undefined : json['hasEbook'],
        'html': json['html'] == null ? undefined : json['html'],
        'id': json['id'] == null ? undefined : json['id'],
        'imageURL': json['imageURL'] == null ? undefined : json['imageURL'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : json['modifiedAt'],
        '_public': json['public'] == null ? undefined : json['public'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(ModelTagDTOFromJSON)),
        'title': json['title'] == null ? undefined : json['title'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ModelBookmarkDTOToJSON(json: any): ModelBookmarkDTO {
    return ModelBookmarkDTOToJSONTyped(json, false);
}

export function ModelBookmarkDTOToJSONTyped(value?: ModelBookmarkDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': value['author'],
        'create_archive': value['createArchive'],
        'create_ebook': value['createEbook'],
        'createdAt': value['createdAt'],
        'excerpt': value['excerpt'],
        'hasArchive': value['hasArchive'],
        'hasContent': value['hasContent'],
        'hasEbook': value['hasEbook'],
        'html': value['html'],
        'id': value['id'],
        'imageURL': value['imageURL'],
        'modifiedAt': value['modifiedAt'],
        'public': value['_public'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(ModelTagDTOToJSON)),
        'title': value['title'],
        'url': value['url'],
    };
}

