/* tslint:disable */
/* eslint-disable */
/**
 * Shiori API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelUserConfig } from './ModelUserConfig';
import {
    ModelUserConfigFromJSON,
    ModelUserConfigFromJSONTyped,
    ModelUserConfigToJSON,
    ModelUserConfigToJSONTyped,
} from './ModelUserConfig';

/**
 * 
 * @export
 * @interface ModelAccount
 */
export interface ModelAccount {
    /**
     * 
     * @type {ModelUserConfig}
     * @memberof ModelAccount
     */
    config?: ModelUserConfig;
    /**
     * 
     * @type {number}
     * @memberof ModelAccount
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelAccount
     */
    owner?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelAccount
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAccount
     */
    username?: string;
}

/**
 * Check if a given object implements the ModelAccount interface.
 */
export function instanceOfModelAccount(value: object): value is ModelAccount {
    return true;
}

export function ModelAccountFromJSON(json: any): ModelAccount {
    return ModelAccountFromJSONTyped(json, false);
}

export function ModelAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : ModelUserConfigFromJSON(json['config']),
        'id': json['id'] == null ? undefined : json['id'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ModelAccountToJSON(json: any): ModelAccount {
    return ModelAccountToJSONTyped(json, false);
}

export function ModelAccountToJSONTyped(value?: ModelAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': ModelUserConfigToJSON(value['config']),
        'id': value['id'],
        'owner': value['owner'],
        'password': value['password'],
        'username': value['username'],
    };
}

