name: "Check mkdocs documentation"

on: workflow_call

jobs:
  mkdocs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0

      - name: check
        run: make docs
        env:
          MKDOCS_EXTRA_FLAGS: --strict
