name: "Check mkdocs documentation"

on: workflow_call

jobs:
  mkdocs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: check
        run: make docs
        env:
          MKDOCS_EXTRA_FLAGS: --strict
