name: "Check mkdocs documentation"

on: workflow_call

jobs:
  mkdocs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0

      - name: check
        run: make docs
        env:
          MKDOCS_EXTRA_FLAGS: --strict
