name: "Check mkdocs documentation"

on: workflow_call

jobs:
  mkdocs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0

      - name: check
        run: make docs
        env:
          MKDOCS_EXTRA_FLAGS: --strict
