name: "Check mkdocs documentation"

on: workflow_call

jobs:
  mkdocs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0

      - name: check
        run: make docs
        env:
          MKDOCS_EXTRA_FLAGS: --strict
