name: "styles-check"

on: workflow_call

jobs:
  styles-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v1
        with:
          bun-version: "1.0.1"

      - name: Check
        run: make styles-check

