name: "styles-check"

on: workflow_call

jobs:
  styles-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup Bun
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1
        with:
          bun-version: "1.0.1"

      - name: Check
        run: make styles-check

