name: "styles-check"

on: workflow_call

jobs:
  styles-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v1
        with:
          bun-version: "1.0.1"

      - name: Check
        run: make styles-check

